# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hi
email: stonemahogany157@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I'll edit the description later.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://StoneMahogany.com" # the base hostname & protocol for your site
twitter_username: StoneMahogany
github_username:  stonemahogany

# Build settings
markdown: kramdown
