# Site settings
title: Hi
email: stonemahogany157@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I'll edit the description later.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://StoneMahogany.com" # the base hostname & protocol for your site
twitter_username: StoneMahogany
github_username:  stonemahogany

# Build settings
markdown: kramdown
